name: task-timer-front-end pipeline

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-session-name: task-timer-front-end-deploy
          role-to-assume: "arn:aws:iam::365562660444:role/github_iam_role"

      - name: Install application dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy
        run: npm ci && npm run deploy
        working-directory: deploy

  send-notification:
    runs-on: ubuntu-latest
    if: always()

    permissions:
      id-token: write

    needs:
      - build-and-deploy

    steps:
      - name: Send Slack notification
        uses: ruchira088/slack-github-action@v1

